### ISSUE TITLE
Make messages optional

### ISSUE THREAD

**Issue by shannonmoeller** [vfile/vfile#22]
I really like how lightweight `vfile` is and that it supports contents as a string. I'd love to be able to use an even lighter version of `vfile` without the `vmessage` features in my [`spiff`](http://npm.im/spiff) package and deprecate my [`vinyl-rw`](http://npm.im/vinyl-rw) module.

Would you be open to a pull request that puts `vfile` and `vmessage` into their own files? I'd make sure the default export was the same:

```js
const vfile = require('vfile'); // no change from the consumer's perspective

const file = require('vfile/file'); // file path, history, and contents creator
const message = require('vfile/message'); // message creator
```

optionally:

```js
import vfile, { file, message } from 'vfile';
```

**Comment by wooorm** [comment]
Yeah! I’d like to externalise vfilemessage already: https://github.com/vfile/vfile/issues/19, so that makes a bunch of sense. I still think `VFile` should come with `.message`, `.info`, and `.fail`, but we could definitely split the library in a `file.js` (thing you want) and `index.js` (thing I want)!
