### ISSUE TITLE
Type tests broken

### ISSUE THREAD

**Issue by wooorm** [vfile/vfile#39]
[Travis fails](https://travis-ci.org/vfile/vfile/jobs/609880888), but locally I cannot reproduce locally:

```
Error: /home/travis/build/vfile/vfile/types/vfile-tests.ts:67:29
423ERROR: 67:29  expect  TypeScript@next compile error: 
424Argument of type 'unknown' is not assignable to parameter of type 'CustomData'.
425
426    at /home/travis/build/vfile/vfile/node_modules/dtslint/bin/index.js:193:19
427    at Generator.next (<anonymous>)
428    at fulfilled (/home/travis/build/vfile/vfile/node_modules/dtslint/bin/index.js:6:58)
429
```

https://github.com/vfile/vfile/blob/9f4180893db6fb4d16fa070fd2ec437118276e21/types/vfile-tests.ts#L66-L69

**Comment by Rokt33r** [comment]
Hmm weird. Typescript@next might be temporarily broken... Our code still looks good to me. Did you try rerun the test?

**Comment by wooorm** [comment]
Yes, I did rerun them, and clearing the caches has no effect!

**Comment by Rokt33r** [comment]
I'm investigating now. I'll leave comments after I learn something.

FYI, I could reproduce the error in my local machine(Pop!_os 19.04, Node v10.15.2)

**Comment by Rokt33r** [comment]
It seems behavior of typescript for `never` keyword has been changed.

Once `never` is returned, the typescript compiler stops checking types of the below code because they are considered as unreachable. I guess it is a part of performance optimization.

And, in `vfile-tests.ts:47`, `file.fail('test')` is returning `never`.(because it throws an error)

So I think we can fix it by 2 ways.
1. Move `file.fail('test')` to most bottom
2. put `file.fail('test')` in a function

And I'll submit an issue about this to typescript repo.

**Comment by Rokt33r** [comment]
@wooorm
It seems intended. So I guess we should change the code.
https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#better-support-for-never-returning-functions
